### ISSUE TITLE
[1.8.8] Registering renderers during preInit cause a crash

### ISSUE THREAD

**Issue by jaredlll08** [MinecraftForge/MinecraftForge#2312]
In 1.7.10 registering renderers were done in preInit(If I am wrong about this, please tell me, it is how I was doing it)

It crashes because Minecraft.getMinecraft().getRenderManager() is null during preInit and according to @RainWarrior, "vanilla caches stuff from the Minecraft class in constructors", here is the crash is produces: http://www.blamejared.com/content/2015-12-26_01-39-28.txt

**Comment by coolAlias** [comment]
Not saying this shouldn't be fixed, but an easy workaround if you want to get your mod going is to register them during the init phase instead.

**Comment by jaredlll08** [comment]
Yea, that is what I am doing, but not everyone knows that, so having it
fixed would be better

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/db3e039b31f1a464ce201b2d8ca92bbd73009c4e

**Comment by RainWarrior** [comment]
Entity renderer registration is still broken so reopening for now.
