### ISSUE TITLE
Recipe loader bails after first bad recipe

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#4013]
While testing my autogenerator for jsons, it was extremely annoying that the loader quits loading after the first bad recipe it sees. This means that you have to relaunch the game tens to hundreds of times to see all your errors.

The loader should just skip to the next recipe if parsing one errors, and present all errors to the modder at once.

**Comment by BlayTheNinth** [comment]
If this is implemented, I would like if it still crashed once all recipes are loaded (instead of *only* logging to console like models do), because otherwise I can see myself and others missing recipe errors since I only actually check the log when I notice something is wrong.

**Comment by mezz** [comment]
Will this be fixed by https://github.com/MinecraftForge/MinecraftForge/pull/4043 or is it a more general issue?
Blay's suggestion (crashing at the end) could be added as a feature after.

**Comment by KnightMiner** [comment]
I have not tested the PR, but based on it's changes I assume not. The issue here is not whether it crashes or not, but that the recipe loader aborts at the first broken recipe

**Comment by Choonster** [comment]
This issue is still present in Forge 1.12-14.21.1.2430. PR #4043 wasn't meant to fix this, it was only meant to log an exception instead of crashing the game.
