### ISSUE TITLE
[Vanilla Bug] getRenderType gets wrong state

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#4747]
In `RenderChunk#rebuildChunk` Line 193 `getRenderType() ` is called on the default state and not on the actual state in the world. Has this any deeper purpose or can I make a PR to correct this issue ?

**Comment by mezz** [comment]
Vanilla seems to avoid combining blocks with different properties together into one. With 1.13 they are split entirely.
Can your case be solved by splitting up the block or is there some complication there?

**Comment by mcenderdragon** [comment]
I am not shure yet, because having this as its on block is kind of wating ids, also blockstates still exists in 1.13 but all metadata relevant stuff should be splitted right ? I currently have a work around (i use a boolean property and set it to the world but never decode it into metas, as it is saved in the tileentity)

**Comment by XFactHD** [comment]
I had the same problem in 1.10.2 and 1.11.2 with a block that changes its state when it is rightclicked. As the values are stored in the tile entity, using multiple blocks for that would be a waste. See #4421 for reference.
