### ISSUE TITLE
[1.13] Lwjgl dll not found/extracted correctly

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#5282]
Yeah agian a path problem because of my UTF8 chars, its my fault I know. The fix for this is easy though. Lwjgl extracts the dll in `%temp%/<libname + username>`. The username is get by the sysproperty "user.name", but in my case java somehow screws this name up, hence the path can not get created as it contains invalid characters.
The fix for this is simply tell lwjgl to use anothert directory:
I used the JVM args: `-Dorg.lwjgl.system.SharedLibraryExtractDirectory=lwjgl_dll` and so the path is `%temp%/lwjgl_dll/`
I dont know if this is the prefered solution, but is is one sultion which works.

**Comment by mcenderdragon** [comment]
I know to add JVM arguments I need to edit the [RunConfig](https://github.com/MinecraftForge/ForgeGradle/blob/FG_3.0/src/common/java/net/minecraftforge/gradle/common/util/RunConfig.java) but they are generated out of jsons and I did not find the json responsible for 1.13. Also maybe there is a better solution, so I did not make a PR jet.

**Comment by XakepSDK** [comment]
Are you sure, that you're using UTF-8, not weird WINDOWS-xxxx?

**Comment by mcenderdragon** [comment]
As I am not assigning the java internal sys properties I can not realy do something about it, the effect is $username is 'Tüp' while user.name is 'T?p' hence it tries to create the folder lwjglT?p (which works) but later it does not find the dlls inside it and crashes. So the easiest solution is to just point the lwjgl library loader to not use the username in the first place. Interesting though all other env vars are correct with Tüp, only user.name is buggy.

**Comment by XakepSDK** [comment]
What OS do you use?

**Comment by mcenderdragon** [comment]
Windows 10 & 8.1. This exact same setup works with older forge versions without any issues.

**Comment by XakepSDK** [comment]
Does this happen to you when you launch game using ForgeGradle?
If so, what does this report in MinecraftForge repository?
Report it in ForgeGradle repository.

I have some tests for you, but you didn't answered me about your system encoding, so, i don't think, that you want to run these tests.
If you want to run these tests, say so.

**Comment by mcenderdragon** [comment]
How do I find out how a system variable is encoded? I choosed this repo and not forge gradle as the run configuration is stored in file in this repo. 
I start via the generated eclipse project hence the JVM args needed to be added to the gradle generated IDE launch configs.

**Comment by XakepSDK** [comment]
Try this:
```java
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.Locale;
import java.util.Map;

public class Test {
    public static void main(String[] args) throws IOException {
        StringBuilder builder = new StringBuilder();
        for (Map.Entry<Object, Object> entry : System.getProperties().entrySet()) {
            builder.append(entry.getKey()).append('=').append(entry.getValue()).append('\n');
        }
        builder.append("Locale=").append(Charset.defaultCharset().displayName(Locale.ENGLISH)).append('\n');
        Path path = Paths.get("properties.txt");
        Files.write(path, builder.toString().getBytes(StandardCharsets.UTF_8), StandardOpenOption.CREATE);
    }
}
```

How to:
1. Create text file named `Test.java`, encoding - UTF-8
2. Put code contents in it
3. `javac Test.java`
4. `java Test`
5. Open resulting `properties.txt` with UTF-8 encoding and search for your property. Does it still contains bad character instead of correct one?
6. What value has `Locale=`?

**Comment by mcenderdragon** [comment]
`Locale=windows-1252` and user.name is also correct.

**Comment by XakepSDK** [comment]
Can you show crash log?

**Comment by mcenderdragon** [comment]
[Log output without fix (crash)](https://gist.github.com/mcenderdragon/8fce947b13323246f73332209436110f)
L[og output with fix](https://gist.github.com/mcenderdragon/f74d788f9192f33803e94b759bc76750)

**Comment by XakepSDK** [comment]
Can you update your JRE? Looks like it's not latest.
Latest is 1.8.0_192

**Comment by mcenderdragon** [comment]
As updating java is a pain in the ass since all path will be wrong no thanks. Your test prooves that it can be made right but somehow isnt.

**Comment by XakepSDK** [comment]
Try this:
```java
import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;

public class Test {
    public static void main(String[] args) throws IOException {
        Path path = Paths.get(System.getProperty("user.name"));
        Path directory = Files.createDirectory(path);
        // Emulate some parts of System#load
        String canonicalPath = new File(directory.toAbsolutePath().toString()).getCanonicalPath();
        String builder = "Path to dir=" + path.toAbsolutePath().toString() +
                '\n' +
                "Path to dir after create=" + directory.toAbsolutePath().toString() +
                '\n' +
                "Canonical path(from file)=" + canonicalPath;
        Files.write(path.resolve("data.txt"), builder.getBytes(StandardCharsets.UTF_8), StandardOpenOption.CREATE);
    }
}
```

File named `data.txt` should be in your `user.name` directory, it must contain some info for more debugging.

**Comment by mcenderdragon** [comment]
the data.txt was in the same dir as the Test.java file. with input:
```
Path to dir=E:\CODE\eclipse\blarg\Tüp
Path to dir after create=E:\CODE\eclipse\blarg\Tüp
Canonical path(from file)=E:\CODE\eclipse\blarg\Tüp
```

**Comment by XakepSDK** [comment]
Thank you! I'm continuing exploring LWJGL for bugs, but it may be already fixed in newer version.

**Comment by XakepSDK** [comment]
Please, try newer JRE:
https://adoptopenjdk.net/releases.html#x64_win

Don't install it
If you use IDEA, just add new JDK and try using it.
If you test it through console, just use `SET PATH=%PATH%;C:\path\to\jdk`(i'm not sure about order), this will set temporarily your PATH variable(in current console session)

**Comment by mcenderdragon** [comment]
Updated java but it still crashed (https://gist.github.com/mcenderdragon/7614d5e37e1bf28b0bf042a6bdbaa716)

**Comment by mcenderdragon** [comment]
Adding `'org.lwjgl.system.SharedLibraryExtractPath': extractNatives.output,` to the build.gradle also fixes this problem, and lwjgl no longer extracts the dlls. The main thing is 
```
org.lwjgl.system.Library# public static void loadSystem(
        Consumer<String> load,
        Consumer<String> loadLibrary,
        Class<?> context,
        String name
```
first it tries to use the lib name as a absolute path, second it uses its own extraction config and 3rd it uses java library path. The 2nd method does not fail at first so dll get extracted but later not found and thus leading to this crash.

**Comment by mcenderdragon** [comment]
I should reopen this as it now happens also for user dev...

**Comment by LexManos** [comment]
Stop using unicode in your paths. 
Feel free to provide a PR that you think would fix this. This doesn't seem to be an issue on our end. It's lwjgl that needs fixing.
