### ISSUE TITLE
[1.13] ICustomModelLoader methods not getting called

### ISSUE THREAD

**Issue by LordMonoxide** [MinecraftForge/MinecraftForge#5466]
Pretty simple - the `onResourceManagerReload` is called when the resource manager is reloaded, but if I comment out that exception so the game starts, the other ones are never thrown.  This is how I was registering an `ICustomModelLoader` in 1.12.2.  Has it changed?

```java
  @SubscribeEvent
  public static void registerModels(final ModelRegistryEvent event) {
    GradientCore.LOGGER.info("REGISTERING CORE MODELS");

    ModelLoaderRegistry.registerLoader(new ICustomModelLoader() {
      @Override
      public void onResourceManagerReload(final IResourceManager resourceManager) {
        throw new RuntimeException("Reload not implemented");
      }

      @Override
      public boolean accepts(final ResourceLocation modelLocation) {
        throw new RuntimeException("accepts " + modelLocation);
        //return false;
      }

      @Override
      public IUnbakedModel loadModel(final ResourceLocation modelLocation) throws Exception {
        throw new RuntimeException("loadModel " + modelLocation);
        //return null;
      }
    });
  }
```

**Comment by williewillus** [comment]
all the model stuff isn't hooked up yet iirc.
you can only use custom model loaders from forge blockstate jsons anyway, and those aren't back in yet

**Comment by LordMonoxide** [comment]
Gotcha, except for this:
> you can only use custom model loaders from forge blockstate jsons anyway

Did that change in the 1.13 update? Unless there was some blockstate magic going on behind the scenes, I was using them without blockstates at all in 1.12.2.

**Comment by tterrag1098** [comment]
No, that's never been true and it won't be in 1.13.

**Comment by williewillus** [comment]
I'll amend that to "you can only use forge transforms and pass custom data to custom models using forge blockstates".

**Comment by LordMonoxide** [comment]
Thanks for the info. feel free to close this, or leave it open as a "todo".

**Comment by jaredlll08** [comment]
Still happening in 1.14.2 from the looks of it with forge `26.0.25`, anything in `onResourceManagerReload` gets called, but the rest doesn't.

**Comment by gigaherz** [comment]
Should be fixed as of 28.1.40 / 5e9380a (1.14.4)

**Comment by ParkerMc** [comment]
I seem to have this bug happening with forge 28.1.113 and 28.1.40. I'm using the same test case that's in the issue. And only `onResourceManagerReload` is running.

**Comment by mura3277** [comment]
I can also confirm this is still happening, but will be made irrelevant with gigas new model PR. For now you can get the current model loaders to work by following gigas solution here: https://pastebin.com/mcjgC6sc

**Comment by gigaherz** [comment]
There's a bug in the workaround I implemented into 1.14.4. in order for the custom model loading to work, you haveto specify *something* that isn't valid in a vanilla blockstates variant, such as "textures", eg: 
```json
{
    "model": "whatever.obj",
    "textures": { "particle": "whatever" }
}
```
