### ISSUE TITLE
Unable To Build Workspace 1.12

### ISSUE THREAD

**Issue by NullSector76** [MinecraftForge/MinecraftForge#5477]
since the release of 1.13 you are unable to setupDecompWorkspace for 1.12.2 or even build previous workspaces. It just says "No such version exists"

**Comment by tterrag1098** [comment]
It was just fixed, try again.

**Comment by NullSector76** [comment]
download newest forge or should older build.gradle work? I am still getting the same error

**Comment by alexbegt** [comment]
Run `./gradlew setupDecompWorkspace --refresh-dependences`

**Comment by NullSector76** [comment]
nope didn't do it. deleting .gradle and trying fresh work space

**Comment by NullSector76** [comment]
that didn't do it either. Unable to get workspace in 1.12.2 after deleting %users%/.gradle and setting up a fresh workspace
https://pastebin.com/Ba90db3W

**Comment by tterrag1098** [comment]
We are still working through build issues. Once it's properly fixed this issue will be closed.

**Comment by NullSector76** [comment]
ok checking back in like 12 hours hope it gets fixed thanks

**Comment by Unnoen** [comment]
Current working solution for **FG1.2 (1.7.x), FG2.1 (1.8.x), FG2.2 (1.9.x - 1.11.x), FG2.3 (1.12.x)** is to do one of the following:

Run `gradlew setupDecompWorkspace --refresh-dependencies`
Or, if that doesn't work, try getting a different version of the MDK and setting that up normally.
A more scorched-earth approach is to delete the FG cache folder most likely at `<user>\.gradle\caches`

It appears gradle may be caching the older version.

For anyone linked here for a version that ISN'T 1.7+, be patient, fixes are coming. The former instructions _should_ work with those versions too once it updates. 

**Update**: FG2.2 (1.9.x - 1.11.x) has received a new build, follow previous instructions if you are still receiving the version error.
**Update 2**: FG2.1 (1.8.x) has received a new build, follow previous instructions if you are still receiving the version error.
**Update 3**: FG1.2 (1.7.x) has received a new build, follow previous instructions if you are still receiving the version error.

**Comment by Dream-Master** [comment]
Are there plans for update 1.7.10 too ?

**Comment by Unnoen** [comment]
It's in the works, as I said, be patient.

**Comment by Khikki** [comment]
> Current working solution for **FG2.2 (1.9.x - 1.11.x), FG2.3 (1.12.x)** is to do one of the following:
> 
> Run `gradlew setupDecompWorkspace --refresh-dependences`
> Or, if that doesn't work, try getting a different version of the MDK and setting that up normally.
> 
> It appears gradle may be caching the older version.
> 
> For anyone linked here for a version that ISN'T 1.9+, be patient, fixes are coming. The former instructions _should_ work with those versions too once it updates.
> 
> **Update**: FG2.2 (1.9.* - 1.11.*) has received a new build, follow previous instructions if you are still receiving the version error.

tell me when he will work again on 1.7.10?

**Comment by MadcowD** [comment]
Fuck yes!

**Comment by Aeronica** [comment]
gradlew --refresh-dependencies
Works for me now

**Comment by tterrag1098** [comment]
This is fixed for FG1.2+

**Comment by Unnoen** [comment]
**Update: All versions from 1.7.10 and upwards are working, please follow the instructions in my previous comment.**

**Comment by Dream-Master** [comment]
i get this error
> ForgeGradle 1.2 does not support forge 1.7.10

**Comment by tterrag1098** [comment]
What forge version are you specifying?

**Comment by Dream-Master** [comment]
1614 for 1.7.10

**Comment by tterrag1098** [comment]
*Be specific*. What *exact* version are you specifying to gradle.

**Comment by Unnoen** [comment]
You don't have the full version specified in the build.gradle, it has to be `1.7.10-10.13.4.1614`

**Comment by Aeronica** [comment]
Just an FYI for those who use travis CI. I had to clear my caches there a couple time between builds to get them working again, but all seems fine for container builds on 1.12.2

**Comment by Dream-Master** [comment]
Most of the mods works now. Will check the rest later. @tterrag1098 @Unnoen thanks

**Comment by NullSector76** [comment]
what about versions from 1.7.2 @Unnoen gradle with forge started in 1.7.2 so it should work all the way back then
