### ISSUE TITLE
[1.13.2] Custom Datapack Issue (Couldn't load function at 'xxx.mcfunction')

### ISSUE THREAD

**Issue by SteveKunG** [MinecraftForge/MinecraftForge#5513]
A custom datapack seems not working with Forge at all.

Step to reproduce :
- Install a datapack to 'datapacks' folder in your map.

A testing datapack :
[magnet_v1.1.zip](https://github.com/MinecraftForge/MinecraftForge/files/2873439/magnet_v1.1.zip)

Error Log :
https://pastebin.com/H8iq3Grs

**Comment by LexManos** [comment]
This should be fixed in the current version.

**Comment by simon816** [comment]
This is still happening on forge `1.13.2-25.0.215`

```
[20:18:16.764] [Server thread/INFO] [minecraft/RecipeManager]: Loaded 524 recipes
[20:18:16.914] [ForkJoinPool.commonPool-worker-2/ERROR] [minecraft/FunctionManager]: Couldn't load function at test:functions/test.mcfunction
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Can not hotload overworld. This must be loaded at all times by main Server.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_212]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) [?:1.8.0_212]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604) [?:1.8.0_212]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) [?:1.8.0_212]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443) [?:1.8.0_212]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_212]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_212]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_212]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_212]
Caused by: java.lang.IllegalArgumentException: Can not hotload overworld. This must be loaded at all times by main Server.
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:158) ~[commons-lang3-3.8.1.jar:3.8.1]
	at net.minecraftforge.common.DimensionManager.initWorld(DimensionManager.java:196) ~[?:?]
	at net.minecraftforge.common.DimensionManager.getWorld(DimensionManager.java:166) ~[?:?]
	at net.minecraft.server.MinecraftServer.getWorld(MinecraftServer.java:987) ~[?:?]
	at net.minecraft.server.MinecraftServer.getCommandSource(MinecraftServer.java:1570) ~[?:?]
	at net.minecraft.advancements.FunctionManager.getCommandSource(FunctionManager.java:189) ~[?:?]
	at net.minecraft.command.FunctionObject.create(FunctionObject.java:49) ~[?:?]
	at net.minecraft.advancements.FunctionManager.lambda$onResourceManagerReload$3(FunctionManager.java:150) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[?:1.8.0_212]
	... 6 more
[20:18:17.283] [Server thread/INFO] [minecraft/AdvancementList]: Loaded 571 advancements
[20:18:17.695] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing start region for dimension minecraft:overworld
```

This only occurs at startup. By using `/reload` once the server is ready, it successfully loads.

**Comment by simon816** [comment]
It's possible to cause a whole server crash if a datapack contains a function tag like the following:

`datapacks/test/data/minecraft/tags/functions/load.json`
```json
{
    "values": [
        "#test:onload"
    ]
}
```

`datapacks/test/data/test/tags/functions/onload.json`
```json
{
    "values": [
        "test:load"
    ]
}
```
`datapacks/test/data/test/functions/load.mcfunction`
```mcfunction
say loaded
```

`datapacks/test/pack.mcmeta`
```json
{
    "pack": {
        "pack_format": 4,
        "description": "test"
    }
}
```

```
21:49:06.576] [Server thread/INFO] [minecraft/RecipeManager]: Loaded 524 recipes
[21:49:06.712] [ForkJoinPool.commonPool-worker-2/ERROR] [minecraft/FunctionManager]: Couldn't load function at test:functions/load.mcfunction
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Can not hotload overworld. This must be loaded at all times by main Server.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_212]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) [?:1.8.0_212]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604) [?:1.8.0_212]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) [?:1.8.0_212]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443) [?:1.8.0_212]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_212]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_212]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_212]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_212]
Caused by: java.lang.IllegalArgumentException: Can not hotload overworld. This must be loaded at all times by main Server.
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:158) ~[commons-lang3-3.8.1.jar:3.8.1]
	at net.minecraftforge.common.DimensionManager.initWorld(DimensionManager.java:196) ~[?:?]
	at net.minecraftforge.common.DimensionManager.getWorld(DimensionManager.java:166) ~[?:?]
	at net.minecraft.server.MinecraftServer.getWorld(MinecraftServer.java:920) ~[?:?]
	at net.minecraft.server.MinecraftServer.getCommandSource(MinecraftServer.java:1430) ~[?:?]
	at net.minecraft.advancements.FunctionManager.getCommandSource(FunctionManager.java:189) ~[?:?]
	at net.minecraft.command.FunctionObject.create(FunctionObject.java:49) ~[?:?]
	at net.minecraft.advancements.FunctionManager.lambda$7(FunctionManager.java:150) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[?:1.8.0_212]
	... 6 more
[21:49:06.728] [Server thread/ERROR] [minecraft/TagCollection]: Couldn't read function tag list test:onload from test:tags/functions/onload.json in data pack test
com.google.gson.JsonParseException: Unknown value 'test:load'
	at net.minecraft.tags.Tag$Builder.deserialize(Tag.java:146) ~[?:?]
	at net.minecraft.tags.TagCollection.reload(TagCollection.java:103) [?:?]
	at net.minecraft.advancements.FunctionManager.onResourceManagerReload(FunctionManager.java:161) [?:?]
	at net.minecraft.resources.SimpleReloadableResourceManager.triggerReloadListeners(SimpleReloadableResourceManager.java:125) [?:?]
	at net.minecraft.resources.SimpleReloadableResourceManager.reload(SimpleReloadableResourceManager.java:101) [?:?]
	at net.minecraft.server.MinecraftServer.loadDataPacks(MinecraftServer.java:1378) [?:?]
	at net.minecraft.server.MinecraftServer.loadDataPacks(MinecraftServer.java:375) [?:?]
	at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:317) [?:?]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:235) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:549) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[21:49:06.728] [Server thread/ERROR] [minecraft/TagCollection]: Couldn't load function tag minecraft:load as it either references another tag that doesn't exist, or ultimately references itself
[21:49:06.729] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.IllegalStateException: Cannot build unresolved tag entry
	at net.minecraft.tags.Tag$TagEntry.populate(Tag.java:226) ~[?:?]
	at net.minecraft.tags.Tag.<init>(Tag.java:37) ~[?:?]
	at net.minecraft.tags.Tag$Builder.build(Tag.java:131) ~[?:?]
	at net.minecraft.tags.TagCollection.reload(TagCollection.java:139) ~[?:?]
	at net.minecraft.advancements.FunctionManager.onResourceManagerReload(FunctionManager.java:161) ~[?:?]
	at net.minecraft.resources.SimpleReloadableResourceManager.triggerReloadListeners(SimpleReloadableResourceManager.java:125) ~[?:?]
	at net.minecraft.resources.SimpleReloadableResourceManager.reload(SimpleReloadableResourceManager.java:101) ~[?:?]
	at net.minecraft.server.MinecraftServer.loadDataPacks(MinecraftServer.java:1378) ~[?:?]
	at net.minecraft.server.MinecraftServer.loadDataPacks(MinecraftServer.java:375) ~[?:?]
	at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:317) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:235) ~[?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:549) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

If the datapack is introduced after the server is loaded, after `/reload` it works as expected
