### ISSUE TITLE
[1.13.2] Custom Entities not appearing

### ISSUE THREAD

**Issue by henkelmax** [MinecraftForge/MinecraftForge#5576]
When spawning a entity with `world.spawnEntity(...)` on a dedicated server, the spawned entity is not appearing on the client side. 

But it seems to exist on the server side (tested by this command `/execute as @e[type=mymod:customentity] run say test`.

This only happens when using the dedicated server (not the internal server).

When spawning a entity on the server, the client receives the following log message: 
`[Client thread/WARN] [minecraft/NetHandlerPlayClient]: Unknown custom packed identifier: fml:play`

**Comment by williewillus** [comment]
this might be #5573 
does it happen in the latest forge build?

**Comment by henkelmax** [comment]
Yes, at first i thought it was caused by #5573 but after it was fixed, it still hasn't worked.

**Comment by williewillus** [comment]
any logs?

**Comment by williewillus** [comment]
from both sides

**Comment by henkelmax** [comment]
Nope. 
This is the only output by the client:
`[Client thread/WARN] [minecraft/NetHandlerPlayClient]: Unknown custom packed identifier: fml:play`

**Comment by itsmeow** [comment]
Same issue. Either they're not being sent to the client or they're being ignored by the client.
Although I am getting this on the internal server as well. Did not see that log output.
I can hear and interact with (collide) entities but I cannot see them at all, not even their shadows.

**Comment by williewillus** [comment]
if you guys set a breakpoint [here](https://github.com/MinecraftForge/MinecraftForge/blob/dd7e7fc1224fa228dc0d57fd07bbbe46199e392c/src/main/java/net/minecraftforge/fml/network/FMLPlayMessages.java#L128) how far does it get?

**Comment by itsmeow** [comment]
![image](https://user-images.githubusercontent.com/10366817/53530917-94230b80-3abf-11e9-97ba-c95152d358da.png)
Seems `entity` is null? This is on client thread

**Comment by itsmeow** [comment]
`                Optional<World> world = LogicalSidedProvider.CLIENTWORLD.get(ctx.get().getDirection().getLogicalSide());
                Entity e = world.map(w->type.handleSpawnMessage(w, msg)).orElse(null);
                if (e == null)
                {
                    return;
                }
` Went line-by-line, returned after finiding entity is null.

**Comment by williewillus** [comment]
hmmm does `world` hold anything? It should have the client world `WorldClient` inside of it

**Comment by itsmeow** [comment]
![image](https://user-images.githubusercontent.com/10366817/53531859-8458f680-3ac2-11e9-92f0-1440bd532a7c.png)
World is null.
![image](https://user-images.githubusercontent.com/10366817/53531895-ab172d00-3ac2-11e9-810a-14cd31da53c9.png)
Network direction "PLAY_TO_CLIENT". Direction logical side: SERVER

**Comment by williewillus** [comment]
@cpw looks like a missing `getOpposite` on the direction once more.

It's confusing that PLAY_TO_CLIENT has logical side server, maybe that method should be renamed to be `getSourceLogicalSide` to make it clear that that's the side used to **send** that network direction, not receive.

**Comment by itsmeow** [comment]
Making a PR to fix this currently - tested after switching the side argument. Seems to have fixed the issue!

**Comment by cpw** [comment]
Grrr. Can you lot make up your mind! https://github.com/MinecraftForge/MinecraftForge/pull/5352
This was already flipped once.

**Comment by cpw** [comment]
I think that the previous PR was incorrect, myself.

**Comment by williewillus** [comment]
a method name change on getDirection or getLogicalSide is probably the clearest way to go tbh
maybe `getLogicalSide` -> `getSendingSide` or `getDirection` -> `getSendingDirection` + doc

**Comment by itsmeow** [comment]
PR #5352 moved the packet side, which caused #5573 - which was resolved via incorrect method of using the side from #5352 causing this issue. And so finally, it has all been resolved with #5578

**Comment by cpw** [comment]
I'm going to disagree quite strongly that #5578 is right. That just _looks_ awful. There is confusion here, and the whole point of NetworkDirection and LogicalSide was to _remove_ the fucking confusion. So, lets fix the bloody confusion.

**Comment by cpw** [comment]
I'm going to agree that we need to figure out a better naming scheme for the methods.

**Comment by itsmeow** [comment]
I agree, the names are bad. But all #5578 does is reverse the side by getting it with `reply()`?

**Comment by itsmeow** [comment]
@cpw Is this handled or should I update my PR with willie's renames?

**Comment by cpw** [comment]
i will be fixing this tonight. Sorry for the delay.

**Comment by cpw** [comment]
Can you confirm this is fixed with 3c73dc2d0b79c2b982145af3cf5a0a72af095a43 ?

**Comment by henkelmax** [comment]
Nope...
Entities are still not appearing when using a dedicated server.
Integrated server is somehow working for me.

**Comment by williewillus** [comment]
can you step through on a debugger on the packet handler on the client, when playing on dedicated server? are both sides updated?

**Comment by henkelmax** [comment]
I am not hitting the breakpoint on the client side...

**Comment by henkelmax** [comment]
I found the bug.
The `FMLPlayMessages.SpawnEntity` packet isn't sent to the client because neither the server nor the client recognizes the packet.
This is caused by the `FMLPlayHandler` class being not loaded and thus not registering the `fml:play` packets.
By just calling the `FMLPlayHandler` class in my mod I triggered the loading of it and it worked just fine.

**Comment by cpw** [comment]
FMLPlay isn't being loaded?????

**Comment by henkelmax** [comment]
`FMLPlayHandler` isn't being loaded because there are no references to the class.

**Comment by henkelmax** [comment]
My workaround is 
```
try {
  Class.forName(FMLPlayHandler.class.getName());
} catch (ClassNotFoundException e) {
  e.printStackTrace();
}
```

**Comment by cpw** [comment]
That'll crash now. Sorry.

**Comment by henkelmax** [comment]
No problem, I'll fix it.
