### ISSUE TITLE
[1.14.4] Hardcore worlds are not deleted if you click "delete world" after dying

### ISSUE THREAD

**Issue by Gamebuster19901** [MinecraftForge/MinecraftForge#5689]
This issue is pretty simple, when you die in hardcore mode, you get an option to delete the world. If you click it, the world is not deleted.

**Comment by Gamebuster19901** [comment]
This issue also affects 1.12.

**Comment by Gamebuster19901** [comment]
This is https://bugs.mojang.com/browse/MC-30646

**Comment by FinnT730** [comment]
If it is a minecraft bug, why post it here?

**Comment by Gamebuster19901** [comment]
> If it is a minecraft bug, why post it here?

Didn't realize until after I created this issue.

**Comment by Gamebuster19901** [comment]
Fixed by 283ece2

**Comment by Unnoen** [comment]
Can confirm this is still an issue. 
Forge 1.14.4-28.1.1
Clicking "Delete World" will kick the player and close the server but *not* delete the world. Loading the world brings you back to the spectate or delete screen.
