### ISSUE TITLE
[1.14.2] WorldEntitySpawner not handling CheckSpawn Result "DENY"

### ISSUE THREAD

**Issue by Xalcon** [MinecraftForge/MinecraftForge#5851]
Pretty much title.
https://github.com/MinecraftForge/MinecraftForge/blob/40bdde204321a3903ec28bf20f8bc7af92df5ad9/patches/minecraft/net/minecraft/world/spawner/WorldEntitySpawner.java.patch#L26-L27

Context:
The WorldEntitySpawner calls `ForgeHooks.canEntitySpawn()` which returns an integer representation of the event result (0 = default, 1 = allow, -1 = deny) but only 0 and 1 are handled.

Looking at the code a few lines lower also creates the impression that canceling the event should do something. The WorldEntitySpawner calls `ForgeEventFactory.doSpecialSpawn()` (that method only returns true if the event was canceled) - but CheckSpawn can't be canceled, causing doSpecialSpawn() to always return false.
https://github.com/MinecraftForge/MinecraftForge/blob/40bdde204321a3903ec28bf20f8bc7af92df5ad9/patches/minecraft/net/minecraft/world/spawner/WorldEntitySpawner.java.patch#L31
https://github.com/MinecraftForge/MinecraftForge/blob/1e0437208b75ef3ee70c378a8aaac426c61601a9/src/main/java/net/minecraftforge/event/ForgeEventFactory.java#L194-L197

**Comment by LexManos** [comment]
Your analysis is completely wrong, however, this should be fixed in 1.14.3

**Comment by Xalcon** [comment]
I've just tested this with a simple deny-all eventhandler. Spawning still occurs.
```
@Mod.EventBusSubscriber
public class EntityBlockingEventHandler
{
    @SubscribeEvent
    public static void onCheckSpawn(LivingSpawnEvent.CheckSpawn event)
    {
        event.setResult(Event.Result.DENY);
    }
}
```
In Forge 27.0.2 the canSpawn value is only checked if the spawning entity is further away than 128 blocks from the closest player. Entities that are closer than that still ignore the event result.
https://github.com/MinecraftForge/MinecraftForge/blob/f4598a97f7a9d4b2daf27d18deb19bf4741a4e2e/patches/minecraft/net/minecraft/world/spawner/WorldEntitySpawner.java.patch#L27

@LexManos  My analysis is probably still wrong, but shouldn't the `canSpawn == -1` be done first/last with a logical `or`?

**Comment by elbakramer** [comment]
I did pretty much the same what @Xalcon did and got the similar issue.
I used `forge-1.14.3-27.0.16_mapped_snapshot_20190621-1.14.2-recomp.jar`.

Specifically, I denied all spawns for `SlimeEntity` inside `LivingSpawnEvent.CheckSpawn` event handler
but still I could find slimes spawning in `Survival` `Superflat` world.

I also agree to @Xalcon's analysis:
- It seems that `if` statement considers `canSpawn` value after testing whether spawning position is 128 block radius far from the player, making that ignore the closer cases.
  - I cannot understand the implications of this.
- I think checking `canSpawn` should be the first step compared to other conditions (by putting it in the first place with logical or, as @Xalcon said)

It seems that current workaround for this is just using `LivingSpawnEvent.SpecialSpawn` event instead (or even `EntityJoinWorldEvent`) and canceling them instead of denying.

**Comment by Xalcon** [comment]
canceling the `SpecialSpawn` event has no effect on spawning itself. It only controls execution of `Entity#onInitialSpawn`, atleast in the context of the `WorldEntitySpawner`. I assume this was also what @LexManos meant in regards of my "wrong analysis". (My IDE had the wrong source mappings configured so it showed me the wrong source code while stepping into the method and I didn't notice that)

Currently, the only way to actually prevent spawning is by using the `EntityJoinWorldEvent`. For now I'm just tagging the entity in the CheckSpawn event and then block the spawning in the join event.
