### ISSUE TITLE
Model Loaders Cannot Be Registered During ModelRegistryEvent

### ISSUE THREAD

**Issue by ChloeDawn** [MinecraftForge/MinecraftForge#7178]
**Description of issue:**

https://github.com/MinecraftForge/MinecraftForge/blob/e3137213e5727b188b9a17bab36113781daa8c1d/src/main/java/net/minecraftforge/client/model/ModelLoaderRegistry.java#L90

The exception thrown here implies that model loaders can safely be registered during `ModelRegistryEvent`, however, this is not true, as the model loader registry is frozen at startup and never unfrozen for subsequent resource reloads, resulting in this exception being printed for model loader registrations during additional resource reloads (e.g `F3+T`) at runtime. The error message either needs updating to omit the `ModelRegistryEvent` suggestion, or the model loader registry needs to be unfrozen on resource reload, with duplicate loader registration ignored for reload listener subscription.

**Minecraft Version:** 1.16.1

**Forge Version:** 32.0.75

**Steps to Reproduce:**
 1. Register a model loader during `ModelRegistryEvent`
 2. Load into a world and reload resources (`F3+T`)
 3. An exception will be logged regarding the loader registration

**Production implementation (1.15.2):**
[TehStoneMan/BetterStorageToo:ClientSetup.java#L90](https://github.com/TehStoneMan/BetterStorageToo/blob/14cc6ce7581bd3c74090a5daab10e493d3dd5ecf/src/main/java/io/github/tehstoneman/betterstorage/client/ClientSetup.java#L90)

**Production exception (31.2.31):** 
```
java.lang.IllegalStateException: Can not register model loaders after models have started loading. Please use FMLClientSetupEvent or ModelRegistryEvent to register your loaders.
	at net.minecraftforge.client.model.ModelLoaderRegistry.registerLoader(ModelLoaderRegistry.java:88) ~[?:?] {re:classloading}
	at io.github.tehstoneman.betterstorage.client.ClientSetup.onModelRegistryEvent(ClientSetup.java:90) ~[?:1.15.2-5.1.0.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_20_ClientSetup_onModelRegistryEvent_ModelRegistryEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168) ~[?:31.2] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$null$9(ModLoader.java:158) ~[?:?] {re:classloading}
	at java.util.HashMap.forEach(HashMap.java:1289) ~[?:1.8.0_252] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:218) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$null$10(ModLoader.java:158) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.preSidedRunnable(ClientModLoader.java:132) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.ModLoader.lambda$loadMods$11(ModLoader.java:158) ~[?:?] {re:classloading}
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:897) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) ~[minecraft-1.15.2-client.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.15.2-31.2.31-launcher.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}
```

**Comment by diesieben07** [comment]
Fixed by https://github.com/MinecraftForge/MinecraftForge/commit/a8e68328c4f521ef5b6d406d5d850b1156457a3f.

**Comment by ChloeDawn** [comment]
That commit does not fix the problem. Looking at that change, subsequent resource reloads are still going to result in loader registration calls on a frozen registry because the registry is never unfrozen for the model registry event. All thst change has done is remove support for the only viable event.

**Comment by gigaherz** [comment]
That is not true. it DOES fix the problem, it just introduced a new issue as a side-effect. I didn't realize mc recreates the model bakery on resource reload. That DOES need to be fixed, but unfreezing isn't the right solution, we just need to make sure the event only fires once.

**Comment by gigaherz** [comment]
Fixed the fix in a3c4ffd2c136830a190bf06381e22aa5c67e4d07
