### ISSUE TITLE
[1.16.2] Mod Loading causes a crash if a dependency is not loaded, instead of showing the error screen.

### ISSUE THREAD

**Issue by Shadows-of-Fire** [MinecraftForge/MinecraftForge#7306]
**Minecraft Version:** 1.16.2

**Forge Version:** 33.0.37

**Logs:** https://gist.github.com/Shadows-of-Fire/11907ea010e7127851222abecba5469c

**Steps to Reproduce:**
 1. Install any mod that has a required dependency without that dependency.
 2. Launch
 3. The game will crash.

**Description of issue:**  This appears to be caused by some change that was made to how mods are loaded in 1.16, as this will not happen in 1.15.  Any dependency error causes a crash (and any startup error might?  Not sure just yet).  This does not happen when using 1.16.2-33.0.22, so some change between 22 and 37 would have caused the problem.

**Comment by ichttt** [comment]
Should be fixed with 33.0.40, see https://github.com/MinecraftForge/MinecraftForge/commit/905102147416112d7819e3cbd6d70e6fd5002a25 (33.0.40 is broken in production right now though, wait for 33.0.41 to test in production or verfiy in a dev enviroment)

**Comment by Shadows-of-Fire** [comment]
This issue is still present in 33.0.42, but the stacktrace has changed.  The error screen is still not shown: https://gist.github.com/Shadows-of-Fire/bf9fde92a948619bec4bc11852b6a051
