### ISSUE TITLE
[1.18.1] EntityInteract & EntityInteractSpecific triple call

### ISSUE THREAD

**Issue by AbsolemJackdaw** [MinecraftForge/MinecraftForge#8390]
**Minecraft Version:** {1.18.1}

**Forge Version:** {39.0.19*}

**Logs:** {no logs.}

**Steps to Reproduce:**
1. Subscribe to the PlayerInteractEvent#EntityInteractSpecific  
2. printline : check clientside and hand  

OR  
1. Subscribe to the PlayerInteractEvent#EntityInteract  
2. printline : check clientside and hand  

**Description of issue:**
- conclude that your console prints six interactions.  

EntityInteractSpecific >
```java
true MAIN_HAND  
true OFF_HAND  
false MAIN_HAND  
false MAIN_HAND  
false OFF_HAND  
false OFF_HAND  
```

EntityInteract >
```java
true MAIN_HAND  
true MAIN_HAND  
true OFF_HAND  
true OFF_HAND  
false MAIN_HAND  
false OFF_HAND  
```

The **EntityInteract** event, trough ForgeHooks#onInteractEntity, is called by both Player#interactOn _and_ MultiPlayerGameMode#interact, being called once, per hand, per side, on Player#interactOn , and once client side, per hand, in MultiPlayerGameMode#interact.
Being able to filter only by hand or side, this undermines calling code client side. 

This is equally true for **EntityInteractSpecific**, but this code is called not twice client side, but twice server side in :  
ServerGamePacketListenerImpl#handleInteract (twice per hand, server side)  
MultiPlayerGameMode#interact (once per hand, client side)

Even though Ive had an issue using one of these events, using the other solved my issue, filtering by hand, and by side I wanted to use.
I believe however, that this is not the intended usage of this event, and therefor the triple call is considered a bug. 
This also affects logging data as shared with me by @Commoble ,  
and appears to have been an issue in 1.16 as well, as shared to my @strikerrocker , confirmed by @AterAnimAvis

**Comment by Kevinlan888** [comment]
mine too, noticed that twice server side.

**Comment by AbsolemJackdaw** [comment]
half of it got solved here already : 
https://github.com/MinecraftForge/MinecraftForge/pull/8598

**Comment by bconlon1** [comment]
I think this may be a recent issue as it was never causing problems until recently (unless it somehow went unnoticed), although not sure how it'd be occurring on 1.16. Since the recent problem I'm running into is the event seems to be called twice as its performing an action twice (despite only being performed for one hand). My theory based on the logs is that on the first call, the event runs on both client and server for both hands, and then it seems to run a second time on server only for both hands.

**Comment by Commoble** [comment]
Still present in 1.19.1, fires twice per hand on the server thread (Level#isClient is false)

```
true MAIN_HAND
true OFF_HAND
false MAIN_HAND
false MAIN_HAND
false OFF_HAND
false OFF_HAND
```
