### ISSUE TITLE
[Forge Server] Functions/Commands and player selectors are not working as intended unless Op'd

### ISSUE THREAD

**Issue by The8BitMonkey** [MinecraftForge/MinecraftForge#9137]
**Minecraft Version:** 1.19.2

**Forge Version:** 43.1.47
- Issue has been present since 43.0.18 and all versions that followed

**Steps to Reproduce:**
 1. In a function write `say hi @s` and have an advancement run that function
 2. When opped the result will be "hi (player name) when not opped the result will be "hi @s"
- this also happened with command blocks when the bug started but seems to have been fixed since then, only functions are affected now from the looks of it

**Description of issue:**
In the latest versions of the Forge Server the connection between the person running the advancement isn't taken into account, so the @s selector doesn't know who to target, it seems as if it's handled as if the server ran it not the player, UNLESS the player is opped in which case it works as expected.

I did a quick test with a vanilla advancement and linked it to a function that simply does /say hello @s, when opped it comes back with "hello The8BitMonkey" but when I remove my op statue I get "hello @s" instead

The last version where everything worked as expected was 43.0.17 but as of 43.0.18 is no longer works without op statue, this could be due to this change noted in the change-log for Forge;

> - 43.0.18 Redirect checks for entity selector use to a permission (#8947)
>            This allows greater flexibility for configuring servers with
>            operator-like permissions to user groups through the permissions API and
>            their permissions handler of choice without needing to grant the
>            vanilla operator permission to any player.
>            The new permission is "forge:use_entity_selectors", which is granted by
>            default to players with permission level 2 (GAMEMASTERS) and above.
>            The hook falls back to checking the permission level if the source of
>            the command is not a ServerPlayer, such as for command blocks and
>            functions.

This clearly breaks vanilla behaviour and results in a lot of datapacks from working as intended when added to the game.

I've attached a video showing the bug in action: https://youtu.be/eJkrgG1bQSc
I've also a datapack to easily reproduce the bug yourself: https://www.dropbox.com/s/80dpejouiec01l1/forge_bug_test.zip?dl=1

**Comment by sciwhiz12** [comment]
Duplicate of #8994

**Comment by sciwhiz12** [comment]
Update to 43.1.3 or later, which contains the PR that fixes the bug (#8995).

Note that the recommendation for users is (and always has been) to always download and use the Latest version/build, especially because bugs get fixed in later versions that are present in older ones. The Recommended version/build is more useful to mod developers for the assurance of binary compatibility (no breaking changes).

When reporting a bug, please explicitly confirm (and state) that the bug is present on the _Latest_ version.

**Comment by The8BitMonkey** [comment]
> Update to 43.1.3 or later, which contains the PR that fixes the bug (#8995).
> 
> Note that the recommendation for users is (and always has been) to always download and use the Latest version/build, especially because bugs get fixed in later versions that are present in older ones. The Recommended version/build is more useful to mod developers for the assurance of binary compatibility (no breaking changes).
> 
> When reporting a bug, please explicitly confirm (and state) that the bug is present on the _Latest_ version.

Hi, thanks for getting back to me.
I am using the latest version (1.19.2 - 43.1.47) and the bug is still there, in my report I was indicating that is has been a bug since 43.0.18 not that I was using that version currently, sorry if that wasn't clear.

I've updated the report with a video of the bug in question (within the latest version of Forge) and a sample datapack to show the bug in question.

If you use the datapack and you're opped, whenever you place a dirt block it will say "Hello (PlayerName)" but if you're not opped then it will simple come back with "Hello @s"

**Comment by sciwhiz12** [comment]
I'm reopening this for further investigation by the Triage Team.
